# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bc360dab45c051b890e130f22894a67f3b017717833b14477f8ecf16cf780e3cb52570b7fc2f774e3501d657d4d6159391ebe8fd25a5bcbcc81db785717db4b

test:
  secret_key_base: d5d1a8655fbd60fe310a65538c33ebaf8e899e0ab12c9fc054ce54aa3d7b67e22d512906fbad7864beeedbb306c1fd7901d4b5b6297012ea2e3b0be84bb39889

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
